version: '2'

services:
  benchmark:
    build:
      context: ./benchmark
      dockerfile: netperf.Dockerfile
    command: /run.sh
    links:
      - netserver
      - nginx
      - proxyd

  nginx:
    build:
      context: ./benchmark
      dockerfile: nginx.Dockerfile
    links:
      - netserver
    expose:
      - "8080"  # for control connection
      - "8081"  # for data connection

  proxyd:
    build:
      context: .
      dockerfile: proxyd.Dockerfile
    image: bibaijin/proxyd:1.1.0
    command: /test.sh
    expose:
      - "8080"  # for control connection
      - "8081"  # for data connection
    links:
      - netserver
    volumes:
      - ./pprof:/pprof

  netserver:
    build:
      context: ./benchmark
      dockerfile: netperf.Dockerfile
    command: netserver -L 0.0.0.0 -D -d
    expose:
      - "12865"  # for control connection
      - "8081"   # for data connection
